Part A

q.1

In [1]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.0.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from seaborn) (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/omshinde/Library/Python/3.14/lib/python/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv('/Users/omshinde/Desktop/Python/Assignment 22/iris.csv')

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [5]:
df.loc[0:4]
df.loc[0:4, ['sepal_length', 'species']]
df.loc[df['species'] == 'setosa']

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [ ]:
df.iloc[0:5]
df.iloc[0:5, 0:2]
df.iloc[[1, 3, 5], [0, 2]]

Q.2

In [ ]:

df[df['sepal_length'] > 5]
df[(df['sepal_length'] > 5) & (df['species'] == 'virginica')]
versicolor_df = df[df['species'] == 'versicolor']
versicolor_df.head()

Q.3

In [ ]:
df.describe()

Mean → Average value of each feature

Std (Standard Deviation) → Spread of data (higher = more variation)

Min → Smallest value

Max → Largest value

In [ ]:
plt.hist(df['sepal_length'])
plt.title("Histogram of Sepal Length")
plt.xlabel("Sepal Length")
plt.ylabel("Frequency")
plt.show()

Shows distribution of values
If tail is on right → right skewed
If symmetric → normal distribution
Spread shows variability

Q.5

In [ ]:
df.groupby('species')['sepal_length'].mean().plot(kind='bar')
plt.title("Average Sepal Length by Species")
plt.xlabel("Species")
plt.ylabel("Sepal Length")
plt.show()

Q.6

In [ ]:
plt.plot(df.index, df['sepal_length'])
plt.title("Sepal Length Trend (Index-based)")
plt.xlabel("Index")
plt.ylabel("Sepal Length")
plt.show()

Q.7

In [ ]:
sns.kdeplot(df['sepal_length'], fill=True)

plt.title("KDE Plot of Sepal Length")
plt.xlabel("Sepal Length")
plt.show()

Part B

In [ ]:
Q.1

In [ ]:
grouped = df.groupby('species').mean()
print(grouped)

Q.2

In [ ]:
grouped['sepal length (cm)'].plot(kind='bar')
plt.title("Average Sepal Length by Species")
plt.xlabel("Species")
plt.ylabel("Sepal Length")
plt.show()

Q.3

In [ ]:
plt.plot(df['sepal length (cm)'], label='Sepal Length')
plt.plot(df['petal length (cm)'], label='Petal Length')

plt.legend()
plt.title("Sepal vs Petal Length")
plt.xlabel("Index")
plt.ylabel("Value")
plt.show()

Q.4

From the visualizations, we can clearly see differences between the species. Virginica has the highest average values, which means it is the largest flower, while setosa has the smallest values and versicolor lies in between. The bar plot shows a clear increasing trend in sepal length from setosa to virginica. In the line chart, petal length shows more variation compared to sepal length. The KDE plot further confirms this, as petal length has a wider spread while sepal length is more concentrated. Overall, these graphs help in understanding the distribution and differences between the species.

Part C

Q1 — Difference between loc and iloc in Pandas
In Pandas, loc and iloc are used for selecting data, but they work differently. The loc function is label-based, which means it selects rows and columns using their names or labels. For example, we can select rows using index labels or filter using conditions. On the other hand, iloc is index-based, meaning it selects data using integer positions (like row number and column number). So, loc is used when we know the labels, while iloc is used when we want to access data by position.

Q2 — Filter rows where a column value is greater than average
To filter rows where a column value is greater than its average, we first calculate the mean of that column and then apply a condition. For example, if we want to filter rows where sepal length is greater than average, we can write:

avg = df['sepal length (cm)'].mean()
filtered_df = df[df['sepal length (cm)'] > avg]

print(filtered_df.head())

Q3 — Purpose of describe() and insights from it
The describe() function in Pandas is used to get a summary of the dataset’s numerical columns. It provides important statistical values like count, mean, standard deviation, minimum, maximum, and quartiles. From this, we can understand the overall distribution of data, check how spread out the values are, and identify any unusual values. For example, the mean tells us the average, standard deviation shows variability, and min/max help us understand the range of the data.